### ISSUE TITLE
为什么我运行不上你的项目，想学习Rx

### ISSUE THREAD

**Issue by xcc3641** [Assassinss/pretty-girl#1]
![image](https://cloud.githubusercontent.com/assets/11666634/12412037/916939a8-bebe-11e5-89c7-4e2b765d1743.png)

**Comment by Assassinss** [comment]
额，这是android studio gradle依赖出现的问题，并不是我项目的问题，这种问题google还是挺多，请google吧。

**Comment by xcc3641** [comment]
嗯嗯 好的 谢谢
